### ISSUE TITLE
wtd.bat报错

### ISSUE THREAD

**Issue by poipo** [peintune/wtd#1]
把项目下下来，直接打开wtd.bat会报错
Exception in thread "main" java.lang.NullPointerException.
请问该怎么办。。

**Comment by poipo** [comment]
错误详情如下

Active code page: 65001
Exception in thread "main" java.lang.NullPointerException
        at com.pub.wtd.util.JavaCompilerTool.<init>(JavaCompilerTool.java:27)
        at com.pub.wtd.common.Engine.<init>(Engine.java:76)
        at com.pub.wtd.common.Main.runCase(Main.java:50)
        at com.pub.wtd.common.Main.main(Main.java:35)

**Comment by peintune** [comment]
应该是你这步没做，试试下面这个步骤：

本地安装好JDK，然后将jdk/lib 目录下的tool.jar文件复制到jre/lib 目录下，否则框架可能报空指针异常。

**Comment by poipo** [comment]
成功了！！谢谢
